### ISSUE TITLE
Python in Excel beta version

### ISSUE THREAD

**Issue by Dinnye001Zz** [microsoft/python-in-excel#9] opened 2023-08-23 11:05 UTC
My problem is that i purchased the personal Office 365 for the new python beta version. I installed it and checked and i have the right version. In the search bar when I search for python it gives back "Insert python" but nothing happens and i dont get the formula.
Can anyone help what could be the problem?

![python](https://github.com/microsoft/python-in-excel/assets/142990370/3ce81811-e65a-4872-bac8-fa4dc76432f1)

**Comment by jflam** [comment] 2023-08-24 00:03
Closed. Dupe of #5

**Closed by jflam** 2023-08-24 00:03 UTC
