### ISSUE TITLE
TypeError when adding a python value and excel value

### ISSUE THREAD

**Issue by cvdstap** [microsoft/python-in-excel#44] opened 2023-10-18 17:26 UTC
The formula is to add 2 integer value's in python :  "=PY(xl("C141")+xl("C142")).
When you enter the formula the error code TypeError occur, but running a second calculation show the correct value.

Not sure why this happen.

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/cvdst/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/cvdst/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

=PY(xl("C141")+xl("C142"))
--

</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/cvdst/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/cvdst/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | 5 | <class 'int'>
-- | -- | --
  | 7 | <class 'int'>
  | simple formula : | 12

</body>

</html>

**Comment by keyur32** [comment] 2023-10-23 15:53
Hi there, I wasn't able to reproduce this.  Do you have a screenshot for example?

**Comment by cvdstap** [comment] 2023-10-24 16:25
Hi, I have included the Excel-file with the strange behaviour. The cell E7 is once calculated as value 12, the next time I calculate the same cell I get the enclosed error (see picture).
![TypeError](https://github.com/microsoft/python-in-excel/assets/1955093/7ea5da84-efdf-40d0-9e8c-cb0d273ded4f)

I hope this [helps](url) to understand the issue.
[TypeErrorxlsx.xlsx](https://github.com/microsoft/python-in-excel/files/13121068/TypeErrorxlsx.xlsx)

**Comment by salabim** [comment] 2023-10-24 17:50
This certainly looks like a bug.

But, it is easy to solve:
Just set the Python Output value (accessible with a right mouse click) of D5  and D6 to "Excel Value" instead of "Python Object"

**Comment by ncalm** [comment] 2023-10-30 15:06
I was able to reproduce it. @salabim is right, if you want to reliably use a reference in the xl method, you should pass it an Excel value, not a Python object. 

Nevertheless, it's not behaving consistently with successive calculations. It cycles between `int + int` and `int + NoneType`. 

![image](https://github.com/microsoft/python-in-excel/assets/23016780/a74ec608-8a89-41ac-9078-d9674969d51c)

**Comment by keyur32** [comment] 2023-12-07 20:05
Update: under investigation. We'll have some changes coming out that may cause this bug to no longer repro as well in the next couple of weeks.

**Comment by keyur32** [comment] 2024-06-27 03:18
Closing this out as it no longer repros

![image](https://github.com/microsoft/python-in-excel/assets/3476087/1c374ecf-f558-4c95-98d7-514eb8cf8c82)

**Closed by keyur32** 2024-06-27 03:18 UTC
Labels: under investigation
